import fs from 'node:fs/promises';
import path from 'node:path';
const turnstile = process.env.PUBLIC_TURNSTILE_SITE_KEY;
const beacon = process.env.PUBLIC_CF_BEACON_TOKEN;
const csp = `default-src 'self'; script-src 'self'${turnstile ? ' https://challenges.cloudflare.com' : ''}${beacon ? ' https://static.cloudflareinsights.com' : ''}; style-src 'self'; img-src 'self' data:; font-src 'self'; media-src 'self'; connect-src 'self'${beacon ? ' https://cloudflareinsights.com' : ''};${turnstile ? ' frame-src https://challenges.cloudflare.com;' : ''} frame-ancestors 'none'; form-action 'self' https://checkout.stripe.com; base-uri 'self'; object-src 'none'; upgrade-insecure-requests`;
// One list, emitted to both `public/_headers` (static assets) and
// `src/lib/security-headers.ts` (the middleware, for server-rendered routes),
// so the two can never drift apart.
const shared = {
  'Content-Security-Policy': csp,
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'accelerometer=(), autoplay=(self), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
};
const headerBlock = Object.entries(shared).map(([key, value]) => `  ${key}: ${value}`).join('\n');
const headers = `/*\n${headerBlock}\n\n/images/*\n  Cache-Control: public, max-age=2592000, stale-while-revalidate=86400\n\n/video/*\n  Cache-Control: public, max-age=2592000, stale-while-revalidate=86400\n\n/downloads\n  Cache-Control: no-store\n  X-Robots-Tag: noindex, nofollow\n\n/cart\n  Cache-Control: no-store\n\n/api/*\n  Cache-Control: no-store\n  X-Robots-Tag: noindex, nofollow\n`;
await fs.mkdir(path.join(process.cwd(), 'public'), { recursive: true });
await fs.writeFile(path.join(process.cwd(), 'public/_headers'), headers);
await fs.writeFile(
  path.join(process.cwd(), 'src/lib/security-headers.ts'),
  `// Generated by scripts/write-headers.mjs. Do not edit by hand.\n` +
    `export const contentSecurityPolicy = ${JSON.stringify(csp)};\n` +
    `export const securityHeaders = ${JSON.stringify(shared, null, 2)};\n`,
);
